version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: todo-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - ~/todo/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
  
  todo-auth:
    image: todo-auth:run
    container_name: todo-auth
    command: --port 4242 --debug
    restart: always
    ports:
    - "0.0.0.0:4242:4242"
    environment:
      MYSQL_URL: mysql:3306
    depends_on:
    - mysql



networks:
  default:
    name: todo
